version: '3'
services:
  app:
    build: .
    ports:
      - 3030:3030
    volumes:
      - ./:/app

  db:
    image: postgres
    volumes:
      - ./testpg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api
    ports:
      - 5432:5432
