version: '3.8'
services:
  app:
    build: .
    ports:
      - 3030:3030
    volumes:
      - ./:/app

  db:
    image: postgres
    volumes:
      - './database/postgreSQL/pgdata:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: api2
    ports:
      - '5432:5432'
