version: '3'
services:
  # app:
  #   build: ./server
  #   ports:
  #     - 3030:3030
  #   volumes:
  #     - ./:/app

  db:
    image: postgres:12-alpine
    volumes:
      - './database/postgreSQL/pgdata:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER: 'me'
      - POSTGRES_PASSWORD: 'password'
      - POSTGRES_DB: 'api2'

    restart: 'on-failure'
